name: Publish Build Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
    
  publish:
    runs-on: self-hosted
    steps:
    - uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: saikiran243275/githubactions:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
